In [1]:
import numpy as np
import pandas as pd

In [2]:
[1,2,3]

[1, 2, 3]

In [3]:
[[ 1, 2, 3],[ 4, 5, 6]]

[[1, 2, 3], [4, 5, 6]]

In [4]:
a = np.array([1, 2, 3])
b = np.array([(1,2,3), (4,5,6)])

In [5]:
a = np.array([1, 2, 3])
b = np.array([(1,2,3), (4,5,6)])

print('a=')
print(a)
print("a's ndim {}".format(a.ndim))
print("a's shape {}".format(a.shape))
print("a's size {}".format(a.size))
print("a's dtype {}".format(a.dtype))
print("a's itemsize {}".format(a.itemsize))

print('')

print('b=')
print(b)
print("b's ndim {}".format(b.ndim))
print("b's shape {}".format(b.shape))
print("b's size {}".format(b.size))
print("b's dtype {}".format(b.dtype))
print("b's itemsize {}".format(b.itemsize))

a=
[1 2 3]
a's ndim 1
a's shape (3,)
a's size 3
a's dtype int32
a's itemsize 4

b=
[[1 2 3]
 [4 5 6]]
b's ndim 2
b's shape (2, 3)
b's size 6
b's dtype int32
b's itemsize 4


In [6]:
c = np.array( [ [1,2], [3,4] ], dtype=complex )
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [7]:
a = np.zeros((2,3))
print('np.zeros((2,3)= \n{}\n'.format(a))

np.zeros((2,3)= 
[[0. 0. 0.]
 [0. 0. 0.]]



In [8]:
b = np.ones((2,3))
print('np.ones((2,3))= \n{}\n'.format(b))

np.ones((2,3))= 
[[1. 1. 1.]
 [1. 1. 1.]]



In [9]:
c = np.empty((2,3))
print('np.empty((2,3))= \n{}\n'.format(c))

np.empty((2,3))= 
[[1. 1. 1.]
 [1. 1. 1.]]



In [10]:
d = np.arange(1, 2, 0.3)
print('np.arange(1, 2, 0.3)= \n{}\n'.format(d))

np.arange(1, 2, 0.3)= 
[1.  1.3 1.6 1.9]



In [11]:
e = np.linspace(1, 2, 7)
print('np.linspace(1, 2, 7)= \n{}\n'.format(e))

np.linspace(1, 2, 7)= 
[1.         1.16666667 1.33333333 1.5        1.66666667 1.83333333
 2.        ]



In [12]:
f = np.random.random((2,3))
print('np.random.random((2,3))= \n{}\n'.format(f))

np.random.random((2,3))= 
[[0.80999946 0.62927696 0.04323999]
 [0.28878319 0.35671179 0.7519614 ]]



In [13]:
zero_line = np.zeros((1,3))
one_column = np.ones((3,1))
print("zero_line = \n{}\n".format(zero_line))
print("one_column = \n{}\n".format(one_column))

a = np.array([(1,2,3), (4,5,6)])
b = np.arange(11, 20)
print("a = \n{}\n".format(a))
print("b = \n{}\n".format(b))

zero_line = 
[[0. 0. 0.]]

one_column = 
[[1.]
 [1.]
 [1.]]

a = 
[[1 2 3]
 [4 5 6]]

b = 
[11 12 13 14 15 16 17 18 19]



In [14]:
b = b.reshape(3, -1)
print("b.reshape(3, -1) = \n{}\n".format(b))

b.reshape(3, -1) = 
[[11 12 13]
 [14 15 16]
 [17 18 19]]



In [15]:
b.reshape(3, -1)

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [16]:
c = np.vstack((a, b, zero_line))
print("c = np.vstack((a,b, zero_line)) = \n{}\n".format(c))

c = np.vstack((a,b, zero_line)) = 
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [11. 12. 13.]
 [14. 15. 16.]
 [17. 18. 19.]
 [ 0.  0.  0.]]



In [17]:
a = a.reshape(3, 2)
print("a.reshape(3, 2) = \n{}\n".format(a))

a.reshape(3, 2) = 
[[1 2]
 [3 4]
 [5 6]]



In [18]:
d = np.hstack((a, b, one_column))
print("d = np.hstack((a,b, one_column)) = \n{}\n".format(d))

d = np.hstack((a,b, one_column)) = 
[[ 1.  2. 11. 12. 13.  1.]
 [ 3.  4. 14. 15. 16.  1.]
 [ 5.  6. 17. 18. 19.  1.]]



In [19]:
e = np.hsplit(d, 3) # Split a into 3
print("e = np.hsplit(d, 3) = \n{}\n".format(e))
print("e[1] = \n{}\n".format(e[1]))

e = np.hsplit(d, 3) = 
[array([[1., 2.],
       [3., 4.],
       [5., 6.]]), array([[11., 12.],
       [14., 15.],
       [17., 18.]]), array([[13.,  1.],
       [16.,  1.],
       [19.,  1.]])]

e[1] = 
[[11. 12.]
 [14. 15.]
 [17. 18.]]



In [20]:
f = np.hsplit(d, (1, 3)) # # Split a after the 1st and the 3rd column
print("f = np.hsplit(d, (1, 3)) = \n{}\n".format(f))

f = np.hsplit(d, (1, 3)) = 
[array([[1.],
       [3.],
       [5.]]), array([[ 2., 11.],
       [ 4., 14.],
       [ 6., 17.]]), array([[12., 13.,  1.],
       [15., 16.,  1.],
       [18., 19.,  1.]])]



In [21]:
g = np.vsplit(d, 3)
print("np.hsplit(d, 2) = \n{}\n".format(g))

# np.vsplit(d, 2) # ValueError: array split does not result in an equal division

np.hsplit(d, 2) = 
[array([[ 1.,  2., 11., 12., 13.,  1.]]), array([[ 3.,  4., 14., 15., 16.,  1.]]), array([[ 5.,  6., 17., 18., 19.,  1.]])]



In [22]:
base_data = np.arange(100, 200)
print("base_data\n={}\n".format(base_data))

print("base_data[10] = {}\n".format(base_data[10]))

base_data
=[100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153
 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171
 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189
 190 191 192 193 194 195 196 197 198 199]

base_data[10] = 110



In [23]:
every_five = np.arange(0, 100, 5)
print("base_data[every_five] = \n{}\n".format(
    base_data[every_five]))

base_data[every_five] = 
[100 105 110 115 120 125 130 135 140 145 150 155 160 165 170 175 180 185
 190 195]



In [24]:
a = np.array([(1,2), (10,20)])
print("a = \n{}\n".format(a))
print("base_data[a] = \n{}\n".format(base_data[a]))

a = 
[[ 1  2]
 [10 20]]

base_data[a] = 
[[101 102]
 [110 120]]



In [25]:
base_data2 = base_data.reshape(10, -1)
print("base_data2 = np.reshape(base_data, (10, -1)) = \n{}\n".format(base_data2))

base_data2 = np.reshape(base_data, (10, -1)) = 
[[100 101 102 103 104 105 106 107 108 109]
 [110 111 112 113 114 115 116 117 118 119]
 [120 121 122 123 124 125 126 127 128 129]
 [130 131 132 133 134 135 136 137 138 139]
 [140 141 142 143 144 145 146 147 148 149]
 [150 151 152 153 154 155 156 157 158 159]
 [160 161 162 163 164 165 166 167 168 169]
 [170 171 172 173 174 175 176 177 178 179]
 [180 181 182 183 184 185 186 187 188 189]
 [190 191 192 193 194 195 196 197 198 199]]



In [26]:
print("base_data2[2] = \n{}\n".format(base_data2[2]))
print("base_data2[2, 3] = \n{}\n".format(base_data2[2, 3]))
print("base_data2[-1, -1] = \n{}\n".format(base_data2[-1, -1]))

base_data2[2] = 
[120 121 122 123 124 125 126 127 128 129]

base_data2[2, 3] = 
123

base_data2[-1, -1] = 
199



In [27]:
print("base_data2[2, :]] = \n{}\n".format(base_data2[2, :]))
print("base_data2[:, 3]] = \n{}\n".format(base_data2[:, 3]))
print("base_data2[2:5, 2:4]] = \n{}\n".format(base_data2[2:5, 2:4]))

base_data2[2, :]] = 
[120 121 122 123 124 125 126 127 128 129]

base_data2[:, 3]] = 
[103 113 123 133 143 153 163 173 183 193]

base_data2[2:5, 2:4]] = 
[[122 123]
 [132 133]
 [142 143]]



In [28]:
base_data = (np.random.random((5, 5)) - 0.5) * 100
print("base_data = \n{}\n".format(base_data))

print("np.amin(base_data) = {}".format(np.amin(base_data)))
print("np.amax(base_data) = {}".format(np.amax(base_data)))
print("np.average(base_data) = {}".format(np.average(base_data)))
print("np.sum(base_data) = {}".format(np.sum(base_data)))
print("np.sin(base_data) = \n{}".format(np.sin(base_data)))

base_data = 
[[-17.00053909 -43.72363017  -3.94219155 -14.67446462  15.34036244]
 [ 35.64384077 -48.11001431 -20.48703292  17.33442217  18.04054625]
 [ 16.42114178 -33.32349928   4.55436278  -9.97850184 -24.1955635 ]
 [ 14.99955296 -43.22161081  29.50867283 -35.03338348 -39.17433021]
 [-42.28920203  18.68673589  26.87751235  25.01170346 -21.74617547]]

np.amin(base_data) = -48.11001431195291
np.amax(base_data) = 35.643840774956395
np.average(base_data) = -6.97925142386465
np.sum(base_data) = -174.48128559661623
np.sin(base_data) = 
[[ 0.96154569  0.2557921   0.71777322 -0.85909491  0.35937758]
 [-0.88491971  0.83389326 -0.99777767 -0.99845124 -0.72360399]
 [-0.65424094 -0.94382479 -0.98753982  0.5258583   0.80589034]
 [ 0.65062739  0.68941877 -0.94393016  0.45810689 -0.9954359 ]
 [ 0.99253082 -0.16210158  0.98490452 -0.12074245 -0.24253023]]


In [29]:
arr = np.arange(1,20)
arr = arr * arr              #Multiplies each element by itself 
print("Multpiles: ",arr)
arr = arr - arr              #Subtracts each element from itself
print("Substracts: ",arr)
arr = np.arange(1,20)
arr = arr + arr              #Adds each element to itself
print("Add: ",arr)
arr = arr / arr              #Divides each element by itself
print("Divide: ",arr)
arr = np.arange(1,20)
arr = arr + 50
print("Add +50: ",arr)

Multpiles:  [  1   4   9  16  25  36  49  64  81 100 121 144 169 196 225 256 289 324
 361]
Substracts:  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
Add:  [ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38]
Divide:  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Add +50:  [51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69]


In [30]:
print("Sqrt: ",np.sqrt(arr))#Returns the square root of each element 
print("Exp: ",np.exp(arr))     #Returns the exponentials of each element
print("Sin: ",np.sin(arr))     #Returns the sin of each element
print("Cos: ",np.cos(arr))     #Returns the cosine of each element
print("Log: ",np.log(arr))     #Returns the logarithm of each element
print("Sum: ",np.sum(arr))     #Returns the sum total of elements in the array
print("Std: ",np.std(arr))     #Returns the standard deviation of in the array

Sqrt:  [7.14142843 7.21110255 7.28010989 7.34846923 7.41619849 7.48331477
 7.54983444 7.61577311 7.68114575 7.74596669 7.81024968 7.87400787
 7.93725393 8.         8.06225775 8.1240384  8.18535277 8.24621125
 8.30662386]
Exp:  [1.40934908e+22 3.83100800e+22 1.04137594e+23 2.83075330e+23
 7.69478527e+23 2.09165950e+24 5.68572000e+24 1.54553894e+25
 4.20121040e+25 1.14200739e+26 3.10429794e+26 8.43835667e+26
 2.29378316e+27 6.23514908e+27 1.69488924e+28 4.60718663e+28
 1.25236317e+29 3.40427605e+29 9.25378173e+29]
Sin:  [ 0.67022918  0.98662759  0.39592515 -0.55878905 -0.99975517 -0.521551
  0.43616476  0.99287265  0.63673801 -0.30481062 -0.96611777 -0.7391807
  0.1673557   0.92002604  0.82682868 -0.02655115 -0.85551998 -0.89792768
 -0.11478481]
Cos:  [ 0.7421542  -0.16299078 -0.91828279 -0.82930983  0.02212676  0.85322011
  0.89986683  0.11918014 -0.77108022 -0.95241298 -0.25810164  0.67350716
  0.98589658  0.39185723 -0.56245385 -0.99964746 -0.5177698   0.44014302
  0.99339038]
Log:  [

In [31]:
base_data = np.floor((np.random.random((5, 5)) - 0.5) * 100)
print("base_data = \n{}\n".format(base_data))

print("base_data.T = \n{}\n".format(base_data.T))
print("base_data.transpose() = \n{}\n".format(base_data.transpose()))

matrix_one = np.ones((5, 5))
print("matrix_one = \n{}\n".format(matrix_one))

minus_one = np.dot(matrix_one, -1)
print("minus_one = \n{}\n".format(minus_one))

print("np.dot(base_data, minus_one) = \n{}\n".format(
    np.dot(base_data, minus_one)))

base_data = 
[[ 12.  34.  24.  48. -41.]
 [-14.   4. -42.  37.  49.]
 [ 12.   5. -43. -18. -35.]
 [ 32.  -6.   1.   6. -28.]
 [ 18.   3. -26. -24. -15.]]

base_data.T = 
[[ 12. -14.  12.  32.  18.]
 [ 34.   4.   5.  -6.   3.]
 [ 24. -42. -43.   1. -26.]
 [ 48.  37. -18.   6. -24.]
 [-41.  49. -35. -28. -15.]]

base_data.transpose() = 
[[ 12. -14.  12.  32.  18.]
 [ 34.   4.   5.  -6.   3.]
 [ 24. -42. -43.   1. -26.]
 [ 48.  37. -18.   6. -24.]
 [-41.  49. -35. -28. -15.]]

matrix_one = 
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

minus_one = 
[[-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]]

np.dot(base_data, minus_one) = 
[[-77. -77. -77. -77. -77.]
 [-34. -34. -34. -34. -34.]
 [ 79.  79.  79.  79.  79.]
 [ -5.  -5.  -5.  -5.  -5.]
 [ 44.  44.  44.  44.  44.]]



In [32]:
print("random: {}\n".format(np.random.random(20)));

print("rand: {}\n".format(np.random.rand(3, 4)));

print("randint: {}\n".format(np.random.randint(0, 100, 20)));

print("permutation: {}\n".format(np.random.permutation(np.arange(20))));

random: [0.71060341 0.76668047 0.0163132  0.67575135 0.42364544 0.96489328
 0.76115355 0.84876509 0.25314854 0.12416551 0.13005697 0.71798265
 0.76080886 0.87509563 0.1388962  0.9114794  0.16617174 0.80551201
 0.84223476 0.89080773]

rand: [[0.76039142 0.0202115  0.67353222 0.53893426]
 [0.04113526 0.30333927 0.69830428 0.4177254 ]
 [0.94472312 0.98537139 0.56881304 0.67700221]]

randint: [47 67 83 93 57 27 48 72 20 37 79 93 98 17 47 10 44 63 12 48]

permutation: [ 2  5 19 12 14 13  7 11  9  3  4 10 18  1  6  8  0 17 16 15]

